#pragma once
#define IDD_CONTROLS_DLG                101
#define IDC_EMPLOYEE_NAME               1002
#define IDC_HOURLY_SALARY               1003
#define IDC_MONDAY1                     1004
#define IDC_TUESDAY1                    1005
#define IDC_WEDNESDAY1                  1006
#define IDC_THURSDAY1                   1007
#define IDC_FRIDAY1                     1008
#define IDC_SATURDAY1                   1009
#define IDC_SUNDAY1                     1010
#define IDC_MONDAY2                     1011
#define IDC_TUESDAY2                    1012
#define IDC_WEDNESDAY2                  1013
#define IDC_THURSDAY2                   1014
#define IDC_FRIDAY2                     1015
#define IDC_SATURDAY2                   1016
#define IDC_SUNDAY2                     1017
#define IDC_PROCESS_BTN                 1018
#define IDC_REGULAR_HOURS               1019
#define IDC_REGULAR_AMOUNT              1020
#define IDC_OVERTIME_HOURS              1021
#define IDC_OVERTIME_AMOUNT             1022
#define IDC_NET_PAY                     1023
#define IDC_STATIC						-1
